version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'aviaot2020'
      MYSQL_DATABASE: 'attendev'
    healthcheck:
      # healthcheck for checking the mysql container is up before starting my app container
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    ports:
        - '3307:3306'
  web:
    image: avishilon22/8200dev_final:latest
    depends_on:
    # starting the container only after the mysql container is up and running
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    working_dir: /app
    links:
      - db